# https://docs.m5stack.com/en/core/AtomS3%20Lite
substitutions:
  device_name: "atoms3-lite-ard"
  device_friendly_name: "AtomS3 Lite"
  device_description: "M5Stack AtomS3 Lite"
  time_timezone: "Asia/Tokyo"

esphome:
  name: ${device_name}
  friendly_name: ${device_friendly_name}
  comment: "${device_description}"
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: 2.0.14
    platform_version: 6.5.0
  variant: esp32s3

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret wifi_fallback_password
    ap_timeout: 15s

captive_portal:

# Enable logging
logger:
  # baud_rate: 0
  # level: VERBOSE

# Enable Home Assistant API
api:

ota:
  platform: esphome

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
  on_ble_advertise:
    then:
      output.turn_on: status_output
  on_scan_end: 
    then:
      output.turn_off: status_output

bluetooth_proxy:
  active: true

# Output that blinks the LED
output:
  - platform: template
    id: status_output
    type: binary
    write_action:
    - if:
        condition:
          lambda: return (state);
        then:
          # - logger.log: Light on
          - light.turn_on:
              id: status_led
              brightness: 70%
              red: 100%
              green: 0%
              blue: 0%
              transition_length: 0s
          - delay: 10ms
          - light.turn_off:
              id: status_led
              transition_length: 0s
        else:
          # - logger.log: Light off
          - light.turn_off: 
              id: status_led
              transition_length: 0s

#G4=IR
#remote_transmitter:
#  pin: GPIO4
#  carrier_duty_percent: 50%


#G35=RGB WS2812B-2020
light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    chipset: WS2812
    pin: 35
    num_leds: 1
    rmt_channel: 1
    id: status_led
    name: ${device_friendly_name} RGB LED

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: GPIO41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed